Update ci-pipeline.yml

diff --git a/nodebrady/ci-pipeline.yml b/nodebrady/ci-pipeline.yml
--- a/nodebrady/ci-pipeline.yml
+++ b/nodebrady/ci-pipeline.yml
@@ -114,12 +114,12 @@ steps:
     #kubectl delete deployments $(kubeNS)
     #kubectl run $(kubeNS) --image=$(registryServerName)/$(imageName):$(imageTag) --port=6379  --kubeconfig /home/vsts/.kube/config
     rm -rf /home/vsts/.kube/create-ipod.yml
-    #kubectl delete pod $(namespaceplaceholder) || echo "error deleting pod.."
+    kubectl delete pod $(namespaceplaceholder)-pod || echo "error deleting pod.."
     echo "Creating image pull secret with kubernetes cluster with sleep 15s.."
     kubectl delete secret npmeut-acr-secret || echo "deleting secret cmd failed.."
     kubectl create secret docker-registry npmeut-acr-secret --docker-server=$(registryName).azurecr.io --docker-username=$(registryLogin) --docker-password=$(registryPassword)  || echo "secret already exists.."
     sleep 15s
-    echo -e "apiVersion: v1\nkind: Pod\nmetadata:\n   name: $(namespaceplaceholder)\nspec:\n   containers:\n    - name: $(namespaceplaceholder)\n      image: $(registryServerName)/$(imageName):latest\n      imagePullPolicy: IfNotPresent\n   imagePullSecrets:\n    - name: $(projectName)-acr-secret" > /home/vsts/.kube/create-ipod.yml
+    echo -e "apiVersion: v1\nkind: Pod\nmetadata:\n   name: $(namespaceplaceholder)\nspec:\n   containers:\n    - name: $(namespaceplaceholder)-pod\n      image: $(registryServerName)/$(imageName):latest\n      imagePullPolicy: IfNotPresent\n   imagePullSecrets:\n    - name: $(projectName)-acr-secret" > /home/vsts/.kube/create-ipod.yml
     cat /home/vsts/.kube/create-ipod.yml
     #echo "printing here ACR_Id........."
     #echo $(az acr show -n $(registryName) -g $(rg) --query id -o tsv)
